# Generated by Django 3.2.8 on 2021-11-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=270)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(max_length=270)),
            ],
        ),
    ]
